'use client';
import {useEffect,useState} from 'react';
type Row={id:string;management_no:string;title:string;review:string;received_date:string;source_page:number;status:string;review_type:string;tags:string[];matched_terms?:string[];eligible:boolean};
type Stats={total:number;eligible:number;detailed:number;excluded:number};
export default function Home(){
 const [q,setQ]=useState(''),[detail,setDetail]=useState(false),[rows,setRows]=useState<Row[]>([]),[stats,setStats]=useState<Stats|null>(null),[selected,setSelected]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('search');
 const [title,setTitle]=useState(''),[review,setReview]=useState(''),[number,setNumber]=useState(''),[confirmed,setConfirmed]=useState(false),[saveKey,setSaveKey]=useState(''),[saved,setSaved]=useState('');
 async function load(query=q,d=detail){setBusy(true);setError('');try{const r=await fetch('/api/cases?q='+encodeURIComponent(query)+'&detail='+d);if(r.status===401)throw new Error('이 자료는 로그인 후 이용할 수 있습니다.');const data=await r.json() as {error?:string;cases:Row[];stats:Stats};if(!r.ok)throw new Error(data.error||'조회 실패');setRows(data.cases);setStats(data.stats);setSelected(data.cases[0]||null);}catch(e){setError(e instanceof Error?e.message:'조회 실패');}finally{setBusy(false);}}
 useEffect(()=>{load('',false);setSaveKey(crypto.randomUUID());},[]);
 async function save(){setBusy(true);setError('');setSaved('');try{const r=await fetch('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,review,management_no:number,confirmed,idempotency_key:saveKey})});const data=await r.json() as {error?:string;cases:Row[];stats:Stats};if(!r.ok)throw new Error(data.error||'저장 실패');setSaved('확정된 검토 결과를 등록했습니다. 다음 검색부터 반영됩니다.');setTitle('');setReview('');setNumber('');setConfirmed(false);setSaveKey(crypto.randomUUID());}catch(e){setError(e instanceof Error?e.message:'저장 실패');}finally{setBusy(false);}}
 return <div><header><div className="brand"><span className="mark">CC</span><div>투자사업 부식검토<small>CORROSION REVIEW · RTS / MOC</small></div></div><span className="private">개인 검토 DB <b>v1.0</b></span></header><main><div className="topline"><div><p className="eyebrow">사례로 검토하고, 근거로 판단합니다</p><h1>부식검토 사례 DB</h1><p className="intro">과거 검토 원문을 찾아 신규 투자 발의의 검토 근거로 활용하세요.</p></div><div className="date">원본 기준일<strong>2026.09.30</strong><span>접수 이력 ~ 2026.09.29</span></div></div><div className="stats"><div><span>전체 이력</span><strong>{stats?.total.toLocaleString()||'—'}<small>건</small></strong></div><div><span>검토완료 · 결과 있음</span><strong>{stats?.eligible.toLocaleString()||'—'}<small>건</small></strong></div><div><span>상세 검토 분류</span><strong>{stats?.detailed.toLocaleString()||'—'}<small>건</small></strong></div><div><span>초안 근거에서 제외</span><strong>{stats?.excluded.toLocaleString()||'—'}<small>건</small></strong></div></div><nav>{[['search','사례 검색'],['guide','신규 발의 검토'],['add','확정 결과 등록']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setError('');if(id==='search')load();}}>{label}</button>)}</nav>{error&&<div role="alert" className="error">{error}</div>}
 {tab==='search'&&<><form className="searchbar" onSubmit={e=>{e.preventDefault();load();}}><input aria-label="검색어" value={q} onChange={e=>setQ(e.target.value)} placeholder="공정, 설비, 유체, 재질 또는 관리번호 검색"/><button className="primary" disabled={busy}>{busy?'조회 중…':'검색'}</button></form><div className="filters"><label><input type="checkbox" checked={detail} onChange={e=>{setDetail(e.target.checked);load(q,e.target.checked);}}/> 상세 검토만 보기</label><div>{['Amine 용접','황산 재질','Caustic PWHT','WHB','Cooling Water'].map(s=><button key={s} onClick={()=>{setQ(s);load(s);}}>{s}</button>)}</div></div><div className="workspace"><section className="results"><div className="panelhead"><b>{q?'검색 결과':'최근 등록 이력'}</b><span>최대 30건 · 관련성순</span></div>{!busy&&!rows.length&&<p className="empty">일치하는 사례가 없습니다. 유체명이나 재질명으로 검색해 보세요.</p>}{rows.map(r=><button key={r.id} className={'case '+(selected?.id===r.id?'selected':'')} onClick={()=>setSelected(r)}><span className="meta">{r.management_no||r.id}<time>{r.received_date}</time></span><strong>{r.title}</strong><span className={'badge '+(!r.eligible?'warn':'')}>{r.review_type}</span></button>)}</section><section className="reader">{selected?<><div className="readermeta">{selected.id} · {selected.source_page?`원문 ${selected.source_page}페이지`:'사용자 확정본'}</div><h2>{selected.title}</h2><div className="tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><div className="reviewlabel">부식검토 결과 원문 <span>{selected.status}</span></div><pre>{selected.review||'검토 결과가 기재되지 않았습니다.'}</pre><div className="notice">과거 사례의 수치와 재질은 당시 조건에 대한 의견입니다. 신규 발의에는 운전조건 및 현행 사내 기준을 확인한 후 적용하세요. PDF 추출 과정에서 줄바꿈·잘림이 있을 수 있습니다.</div></>:<p className="empty">사례를 선택하면 검토 원문을 확인할 수 있습니다.</p>}</section></div></>}
 {tab==='guide'&&<section className="guide"><span className="eyebrow">CHATGPT에서 검토 초안 작성</span><h2>발의 내용을 입력하면, 근거 사례와 함께 검토합니다.</h2><p>이 플러그인을 연결한 ChatGPT 대화에서 아래처럼 요청하세요. 이 화면에서는 사례 검색과 확정본 등록을 제공합니다.</p><blockquote>이 투자 발의의 부식검토 초안을 작성해 줘.<br/>제목: …<br/>변경 목적 및 범위: …<br/>유체 / 온도 / 압력 / 농도: …<br/>기존·변경 재질 및 열처리 상태: …</blockquote><div className="steps"><div><b>01 · 근거 검색</b><p>한·영 키워드로 관련 사례를 찾고 검토완료 사례의 원문을 비교합니다.</p></div><div><b>02 · 조건 비교</b><p>재질·유체·운전조건의 차이와 추가 확인사항을 분리합니다.</p></div><div><b>03 · 초안 작성</b><p>문서용 검토안, 근거 사례, 적용 조건을 대화에서 제공합니다.</p></div></div><p className="notice">검토 초안은 자동으로 DB에 등록되지 않습니다. 검토를 마친 결과만 ‘확정 결과 등록’에서 저장하세요.</p></section>}
 {tab==='add'&&<section className="entry"><h2>확정된 부식검토 결과 등록</h2><p>제목과 최종 검토 결과를 등록하면 이후 사례 검색에 반영됩니다.</p><form onSubmit={e=>{e.preventDefault();save();}}><label>투자 제목<input required maxLength={2000} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>관리번호 <span>선택</span><input value={number} onChange={e=>setNumber(e.target.value)}/></label><label>최종 부식검토 결과<textarea required maxLength={30000} rows={12} value={review} onChange={e=>setReview(e.target.value)}/></label><label className="confirm"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> 검토를 마친 확정본임을 확인했습니다.</label><button className="primary" disabled={busy||!confirmed}>{busy?'저장 중…':'확정본 등록'}</button>{saved&&<p role="status" className="success">{saved}</p>}</form></section>}
 <footer>원본: Corrosion Control팀 RTSMOC 부식검토처리현황 파악 · 162페이지<br/>분류는 검색 보조용이며 기술적 적합성 판정을 의미하지 않습니다.</footer></main></div>;
}
